name: flutter_live_shopping
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  go_router: ^17.1.0
  dio: ^5.9.1
  google_fonts: ^8.0.1
  intl: ^0.20.2
  json_annotation: ^4.10.0
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.12.0
  shimmer: ^3.0.0
  video_player: ^2.10.1
  chewie: ^1.13.0
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  json_serializable: ^6.12.0

flutter:

  uses-material-design: true

  assets:
    - assets/mock-api-data.json
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
